version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  assignees:
  - destos
  ignore:
  - dependency-name: pre-commit
    versions:
    - "> 1.13.0"
