version: '3.7'

services:
    web:
        build:
            context: .
            dockerfile: docker/dockerfiles/web
            args:
                - POETRY_ARGS=  # allow dev install
        working_dir: /srv/app
        command: ./manage.py runserver_plus 0.0.0.0:8000
        user: ${UID:-1000}  # user id or default
        restart: unless-stopped
        volumes:
            - ".:/srv/app"
            - "python-packages:/usr/local/lib/python3.7/site-packages"
            - "upload-volume:/var/www/media"
        ports:
            - '8000:8000'
        environment:
            DEBUG: 'true'
            ALLOWED_HOSTS: '*'
            DATABASE_URL: postgres://postgres:postgres@toolhub-db/toolhub
            MEDIA_ROOT: /var/www/media/
            STATIC_ROOT: /var/www/static/
            PYTHONUNBUFFERED: 1
        depends_on:
            - db
        env_file: .dockerenv
        networks:
            app_net:
                aliases:
                    - toolhub-web
    db:
        image: postgres:latest
        ports:
            - "${DB_PORT-0}:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: toolhub
            PGDATA: /var/lib/postgresql/data/pgdata
        volumes:
            - "db-volume:/var/lib/postgresql/data/pgdata"
            - "./docker/init/db:/docker-entrypoint-initdb.d"
        networks:
            app_net:
                aliases:
                    - toolhub-db

volumes:
    db-volume:
        name: toolhub_db-volume
    python-packages:
        name: toolhub_python-packages
    upload-volume:
        name: toolhub_upload-volume

networks:
    app_net:
        name: toolhub-net
        driver: bridge
