version: '3.7'

services:
    web:
        build:
            context: .
            dockerfile: docker/dockerfiles/web
            args:
                - POETRY_ARGS=  # allow dev install
        working_dir: /srv/app
        # command: ./manage.py shell
        command: python -m http.server
        # command: ./manage.py runserver_plus 0.0.0.0:8000
        user: ${UID:-1000}  # user id or default
        restart: unless-stopped
        volumes:
            - ".:/srv/app"
            - "python-packages:/usr/local/lib/python3.7/site-packages"
            - "upload-volume:/var/www/media"
        ports:
            - '8000:8000'
        environment:
            DEBUG: 'true'
            ALLOWED_HOSTS: '*'
            DATABASE_URL: postgres://postgres:postgres@toolhub-db/toolhub
            SEARCH_HOST: toolhub-search:9200
            MEDIA_ROOT: /var/www/media/
            STATIC_ROOT: /var/www/static/
            PYTHONUNBUFFERED: 1
        depends_on:
            - db
            - search
        env_file: .dockerenv
        networks:
            app_net:
                aliases:
                    - toolhub-web
    db:
        image: postgres:latest
        ports:
            - "${DB_PORT-0}:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: toolhub
            PGDATA: /var/lib/postgresql/data/pgdata
        volumes:
            - "db-volume:/var/lib/postgresql/data/pgdata"
            - "./docker/init/db:/docker-entrypoint-initdb.d"
        networks:
            app_net:
                aliases:
                    - toolhub-db
    search:
        image: elasticsearch:6.5.0
        ports:
            - "${SEARCH_PORT-0}:9200"
        environment:
            - cluster.name=docker-cluster
            - discovery.type=single-node
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            - search-volume:/usr/share/elasticsearch/data
        networks:
            app_net:
                aliases:
                    - toolhub-search

volumes:
    db-volume:
        name: toolhub_db-volume
    python-packages:
        name: toolhub_python-packages
    upload-volume:
        name: toolhub_upload-volume
    search-volume:
        name: toolhub_search-volume

networks:
    app_net:
        name: toolhub-net
        driver: bridge
