#!/bin/bash
set -e
script_base=$(dirname "$0")
cd $script_base/..

source $script_base/tools

POSITIONAL=()
while [[ $# -gt 0 ]]; do
    key="$1"
    case $key in
        -h|--help|?)
            echo "Run a specific service in interactive debug mode."
            echo
            cecho "Usage: $(basename $0) <options> SERVICE" default bold
            echo
            echo "Options:"
            echo "  -h  --help          This help message"
            echo
            echo "Run 'docker-compose up --help' to see more options"
            exit 0
            ;;
        *)
            POSITIONAL+=("$key")
            ;;
    esac
    shift
done
set -- "${POSITIONAL[@]}"

service=$1
if [[ ! $service ]]; then
    cecho "You must provide the name of the service you would like to debug." red bold
    exit 1;
fi

cecho "Restarting '$service' in interactive debug mode. Kill the process to return to normal." yellow bold
docker-compose stop $service
docker-compose run --name toolhub_debug-$service --rm --service-ports $service \
    && docker-compose up -d $service
