#!/bin/bash
set -e
script_base=$(dirname "$0")
cd $script_base/..

source $script_base/tools

no_save=
no_input=
dev=
uninstall_type=

POSITIONAL=()
while [[ $# -gt 0 ]]; do
    key="$1"
    case $key in
        -y|--no-input)
            no_input=1
            ;;
        --no-save)
            no_save=1
            ;;
        --dev)
            dev=1
            ;;
        -h|--help|?)
            echo "Uninstall a package."
            echo
            cecho "Usage: $(basename $0) <options> <PKG TYPE> <PKG NAME>..." default bold
            echo
            echo "Package Types:"
            echo "  py  | python"
            # echo "  js | javascript"
            echo
            echo "Options:"
            echo "      --dev           Un-install package for development only (JS and Python only)"
            echo "      --no-save       Do not save package changes, un-install only (JS and Python only)"
            echo "  -y  --no-input      Assume yes for all user input"
            echo "  -h  --help          This help message"
            exit 0
            ;;
        *)
            POSITIONAL+=("$key")
            ;;
    esac
    shift
done
set -- "${POSITIONAL[@]}"

uninstall_type=$1
shift
args=$@

if [ ! "$args" ]; then
    cecho "You must provide at least one package name to install." red bold
    exit 2
fi

case $uninstall_type in
    py|python)
        if [ "$no_save" ]; then
            args="$args --dry-run"
        fi
        if [ "$dev" ]; then
            docker-compose exec -u root web python -m poetry remove --dev $args
        else
            docker-compose exec -u root web python -m poetry remove $args
        fi
        ;;
    js|javascript)
       ;;
    *)
        cecho "You must provide a valid package type to un-install. Use '$(basename $0) --help' for most information." yellow bold
        exit 1
esac
