#!/bin/bash
set -e
script_base=$(dirname "$0")
cd $script_base/..

source $script_base/tools

no_input=

POSITIONAL=()
while [[ $# -gt 0 ]]; do
    key="$1"
    case $key in
        -y|--no-input)
            no_input=1
            ;;
        -h|--help|?)
            echo "Reset environment after a large repository update."
            echo
            cecho "Usage: $(basename $0) <options> <SERVICE>]" default bold
            echo
            echo "Services:"
            echo "$(docker-compose config --services)"
            echo
            echo "Options:"
            echo "  -y  --no-input      Assume yes for all user input"
            echo "  -h  --help          This help message"
            exit 0
            ;;
        *)
            POSITIONAL+=("$key")
            ;;
    esac
    shift
done
set -- "${POSITIONAL[@]}"

if [ ! "$no_input" ]; then
    cecho "This will delete many files and volumes and may be destructive to work in progress." yellow bold
    read -n1 -r -p "Press 'Y' to continue or any other key to cancel..." key
    echo
    if [ ! "$key" ] || [[ "yY" != *"$key"* ]]; then
        echo
        cecho "Aborting." red
        exit 0
    fi
fi

$script_base/cleanup --no-input

echo
cecho "Rebuilding environment..." default bold
docker-compose build

echo
cecho "Running database migrations..." default bold
$script_base/start -d web db
$script_base/migrate
$script_base/stop
