# Generated by Django 2.1.1 on 2018-10-05 03:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_auto_20181003_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clearancepermission',
            name='tool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='tools.UserTool'),
        ),
        migrations.AlterField(
            model_name='toolhistory',
            name='tool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='tools.UserTool'),
        ),
        migrations.AlterField(
            model_name='toolhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tool_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='toolphoto',
            name='tool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='tools.UserTool'),
        ),
        migrations.AlterField(
            model_name='toolphoto',
            name='uploading_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_photos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usertool',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='usertool',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tools', to=settings.AUTH_USER_MODEL),
        ),
    ]
