# Generated by Django 2.1.1 on 2018-10-10 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0003_auto_20181005_0355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertool',
            old_name='taxonomoies',
            new_name='taxonomies',
        ),
    ]
