# Generated by Django 2.1.1 on 2018-10-12 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0004_auto_20181011_0333'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='toolhistory',
            options={'get_latest_by': 'created', 'ordering': ('-created',), 'verbose_name': 'Tool History', 'verbose_name_plural': 'Tool Histories'},
        ),
        migrations.RenameField(
            model_name='usertool',
            old_name='taxonomoies',
            new_name='taxonomies',
        ),
        migrations.AlterModelOptions(
            name='toolphoto',
            options={'get_latest_by': 'created', 'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='usertool',
            options={'get_latest_by': 'created', 'ordering': ('-created',), 'verbose_name': 'Tool', 'verbose_name_plural': 'Tools'},
        ),
    ]
