# Generated by Django 2.1.1 on 2018-10-16 04:56

from django.db import migrations
import tagulous.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0005_auto_20181012_0428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertool',
            name='taxonomies',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, blank=True, force_lowercase=False, help_text='Enter a comma-separated tag string', related_name='tools', space_delimiter=False, to='tools.ToolTaxonomy', tree=True),
        ),
    ]
