# Generated by Django 2.1.1 on 2018-10-13 03:26

import colorful.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0005_auto_20181012_0428'),
    ]

    operations = [
        migrations.AddField(
            model_name='tooltaxonomy',
            name='color',
            field=colorful.fields.RGBColorField(null=True),
        ),
    ]
