# Generated by Django 2.1.1 on 2018-10-16 05:48

import colorful.fields
from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0006_auto_20181016_0534'),
    ]

    operations = [
        migrations.AddField(
            model_name='tooltaxonomy',
            name='color',
            field=colorful.fields.RGBColorField(null=True),
        ),
        migrations.AlterField(
            model_name='usertool',
            name='description',
            field=markdownx.models.MarkdownxField(blank=True),
        ),
    ]
