# Generated by Django 2.1.1 on 2018-10-14 20:41

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0006_tooltaxonomy_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertool',
            name='description',
            field=markdownx.models.MarkdownxField(blank=True),
        ),
    ]
