# Generated by Django 2.1.1 on 2018-10-22 01:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tools', '0007_auto_20181016_0548'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clearancepermission',
            options={'get_latest_by': 'created', 'ordering': ('-created',), 'verbose_name': 'Clearance', 'verbose_name_plural': 'Clearances'},
        ),
        migrations.AlterField(
            model_name='usertool',
            name='clearance',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Available to all'), (1, 'Owner cleared users only'), (2, 'Cleared users can approve anyone')], default=0, help_text='Who is allowed to clear a user to use this tool', verbose_name='Clearance'),
        ),
        migrations.AlterUniqueTogether(
            name='clearancepermission',
            unique_together={('tool', 'cleared_user')},
        ),
    ]
