# Generated by Django 2.1.7 on 2019-03-12 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0007_auto_20181106_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolphoto',
            name='file',
            field=models.ImageField(upload_to='%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='toolphoto',
            name='tool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='tools.UserTool'),
        ),
    ]
